import Head from "next/head";
import styles from "../styles/Home.module.css";

import { Dashboard } from "../components/Dashboard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Music-player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  );
}
